# HotpotQA pipeline configuration
# Inherits defaults from base_config.yaml

mode: json
pipeline:
  data_path: data/json/hotpotqa.json
  output_dir: output/json/hotpotqa
  dataset_type: hotpotqa
  extraction_mode: chunking
  chunk_size: 120
